spring:
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB
  threads:
    virtual.enabled: true
  devtools:
    remote.secret: teste 
    add-properties: true
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:h2:mem:pizza;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  h2:
    console.enabled: true
  sql:
    init:
      platform: h2
      mode: always
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method

app:
  # Should be changed to your own path in your Linux or Windows
  temp-storage: ${user.home}/apps/spring-batch-demo/temp_storage_spring_batch/ 